import type { Metadata } from "next";
import { ThemeProvider } from "@/components/theme-provider";
import { PT_Sans } from "next/font/google";
import { SpeedInsights } from "@vercel/speed-insights/next";
import Header from "./components/Header";
import NavImage from "./components/NavImage";
import Footer from "./components/Footer";
import '@/app/styles/globals.css'


const pt_sans=PT_Sans({subsets:['latin'],style:'normal' , weight:'400'});

export const metadata: Metadata = {
  title: " Next-js App",
  description: "Generated by create next app",
};




export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="scroll-smooth" suppressHydrationWarning lang="en">
      <body
        className={`${pt_sans.className} background   dark:bg-dark-mode relative  `}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Header />
          <NavImage />
          {children}

          <Footer />

        </ThemeProvider>
        <SpeedInsights />

      </body>
    </html>
  );
}
