import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { SpeedInsights } from "@vercel/speed-insights/next";
import "./styles/globals.css";
import Header from "./components/Header";
import { ModeProvider } from "./contexts/ModeContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: " Next-js App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
   <ModeProvider>

     <html className="scroll-smooth" lang="en">
      <body className={`${inter.className} background dark:bg-dark-mode relative  `}>
        <Header/>

        {children}

        <SpeedInsights />
      </body>
    </html>
   </ModeProvider>
  );
}
